language: ruby
rvm:
  - 2.4.1

sudo: false
cache: bundler

branches:
  only:
  - development

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

script:
- bundle exec jekyll build
- cp CNAME _site

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: development
