language: ruby
rvm:
  - 2.4.1

script:
- bundle exec jekyll build
- sed -i '/docs/d' .gitignore
- mv _site docs

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master # GitHub Pages only serves user sites from master
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: development

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

branches:
  only:
  - development

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
