title: Nadav Ami
tagline: 
url: https://nadav.ca
baseurl: ""
highlighter: rouge
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME', 'vendor']


author:
  name: Nadav Ami
  url: https://nadav.ca
  email: hello@nadav.ca
  github: nadavami

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-gist
