title: Nadav Ami
tagline: 
url: https://nadav.ca
paginate: 1
baseurl: ""
highlighter: true
permalink: pretty

author:
  name: Nadav Ami
  url: https://nadav.ca
  email: hello@nadav.ca

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
